# Generated by Django 4.0.5 on 2022-06-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_genre_alter_airplay_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='genres',
            field=models.ManyToManyField(to='main_app.genre'),
        ),
    ]
